#!/bin/bash

set -e

# pick the anatomical image, upsample to higher resolution, and set to zero:
mrgrid anat.nii regrid -voxel 0.5 - | mrconvert - -axes 0,1,2 - | mrcalc - 0 -mult phantom.mif -force


# draw 3 spheres of different intensities and locations on it:
mredit phantom.mif -sphere 160,256,256 60 100 -sphere 200,290,256 30 200 -sphere 120,210,256 20 30 -sphere 125,300,250 5 200 -sphere 100,300,250 3 200 -sphere 80,300,250 0.9 200 -sphere 125,275,250 5 50


# (optional) draw 3 orthogonal planes filled with zeros of different thicknesses and locations:
mrcalc phantom.mif 0 -mult tmp.mif -force
mredit tmp.mif -plane 0 185:195 50 -plane 1 200:205 50 -plane 2 190:210 50
mrcalc phantom.mif tmp.mif -and tmp.mif phantom.mif -if phantom.mif -force

